create table login_vacc(username character varying(100) primary key,password character varying(100),repassword 
/
character varying(100),mob character varying(10),email character varying(100),type numeric(1),member_no numeric(5),father_name character varying(100),mother_name character varying(100),address character varying(4000));
/
insert into login_vacc values('admin','admin','veer','555555555','vp@gmail.com',2,1,'god','godess','Java Heaven');
/
create table child_vacc(child_id numeric(10) primary key,child_name character varying(4000),child_age character varying(100),alert character varying(50),username character varying(100));


create table child_schedule(username character varying(1000),child_name character varying(4000),child_id numeric(10),taken_vaccine character varying(4000));


CREATE TABLE  VACC_INFO 
   (AGE character varying(4000), 
	VACCINE character varying(4000),description character varying(4000),disease character varying(4000)
   );


insert into vacc_info values('Birth','BCG','BCG, or bacille Calmette-Guerin, is a vaccine for tuberculosis (TB) disease. Many foreign-born persons have been BCG-vaccinated. BCG is used in many countries with a high prevalence of TB to prevent childhood tuberculous meningitis and miliary disease. However, BCG is not generally recommended for use in the United States because of the low risk of infection with Mycobacterium tuberculosis, the variable effectiveness of the vaccine against adult pulmonary TB, and the vaccine?s potential interference with tuberculin skin test reactivity. The BCG vaccine should be considered only for very select persons who meet specific criteria and in consultation with a TB expert.','Eye disease,HIV,ErythmaNodosom');


insert into vacc_info values('Birth','Oral Polio Vaccine - 1st Dose','Oral polio vaccine (OPV) is a live-attenuated vaccine, produced by the passage of the virus through non-human cells at a sub-physiological temperature, which produces spontaneous mutations in the viral genome.Polio Disease are contagious illness that used to be very common in the United States. Causes of Polio-Poliovirus,Poliovirus is a highly contagious virus that only affects humans, muscle aches, and abdominal pain are a few of the possible symptoms of polio.How do you diagnose polio?in order to diagnose polio, the doctor will ask the patient several questions and perform a physical exam. This article takes an in-depth look at the process of diagnosing polio.','Polio');
/
stop

insert into vacc_info values('Birth','Hepatitis B Vaccine 1st dose','Hepatitis B is a potentially deadly infection of the liver that kills about 500,000 to 700,000 people each year, mostly in developing countries. The virus is spread perinatally from an infected mother to her infant at birth, from child to child, through unsafe injections and transfusions, and through sexual contact. Currently, there is no effective treatment for the disease. Hepatitis B vaccines have been shown to be about 95 percent protective against the disease when used correctly. Hepatitis B resources on the Vaccine Resource Library were mainly gathered during PATH?s Children?s Vaccine Program, which conducted activities with hepatitis B vaccine.','cancer,jaundice (yellowing of the eyes and skin), dark urine, loss of appetite,AIDS-causing virus, HIV');


insert into vacc_info values('2 weeks','BCG','BCG, or bacille Calmette-Guerin, is a vaccine for tuberculosis (TB) disease. Many foreign-born persons have been BCG-vaccinated. BCG is used in many countries with a high prevalence of TB to prevent childhood tuberculous meningitis and miliary disease. However, BCG is not generally recommended for use in the United States because of the low risk of infection with Mycobacterium tuberculosis, the variable effectiveness of the vaccine against adult pulmonary TB, and the vaccine?s potential interference with tuberculin skin test reactivity. The BCG vaccine should be considered only for very select persons who meet specific criteria and in consultation with a TB expert.','Eye disease,HIV,ErythmaNodosom');


insert into vacc_info values('2 weeks','Oral Polio Vaccine - 1st Dose','Oral polio vaccine (OPV) is a live-attenuated vaccine, produced by the passage of the virus through non-human cells at a sub-physiological temperature, which produces spontaneous mutations in the viral genome.Polio Disease are contagious illness that used to be very common in the United States. Causes of Polio-Poliovirus,Poliovirus is a highly contagious virus that only affects humans, muscle aches, and abdominal pain are a few of the possible symptoms of polio.How do you diagnose polio?in order to diagnose polio, the doctor will ask the patient several questions and perform a physical exam. This article takes an in-depth look at the process of diagnosing polio.','Polio');


insert into vacc_info values('6 weeks','Hepatitis B Vaccine 1st dose','Hepatitis B is a potentially deadly infection of the liver that kills about 500,000 to 700,000 people each year, mostly in developing countries. The virus is spread perinatally from an infected mother to her infant at birth, from child to child, through unsafe injections and transfusions, and through sexual contact. Currently, there is no effective treatment for the disease. Hepatitis B vaccines have been shown to be about 95 percent protective against the disease when used correctly. Hepatitis B resources on the Vaccine Resource Library were mainly gathered during PATH?s Children?s Vaccine Program, which conducted activities with hepatitis B vaccine.','cancer,jaundice (yellowing of the eyes and skin), dark urine, loss of appetite,AIDS-causing virus, HIV');


insert into vacc_info values('6 weeks','Haemophilus Influenzae B Vaccine - 1st Dose','Haemophilus influenzae type b (Hib) Hib mainly affects children under five years of age and is a significant cause of meningitis (inflammation of the covering of the brain) and bacterial pneumonia in children.Hib does not cause the ?flu?. Hib can leave children with permanent neurological disabilities, including brain damage, hearing loss, and mental retardation.Hib normally establishes itself in the nose or upper throat and is spread through sneezing, coughing, or speaking closely with an infected person. Children often carry Hib bacteria without showing any signs or symptoms(asymptomatic carriers), but they can still infect others.','Flu,HIV,brain damage,hearing loss,mentalretardation');


insert into vacc_info values('6 weeks','Oral Polio Vaccine - 2nd Dose','Oral polio vaccine (OPV) is a live-attenuated vaccine, produced by the passage of the virus through non-human cells at a sub-physiological temperature, which produces spontaneous mutations in the viral genome.Polio Disease are contagious illness that used to be very common in the United States. Causes of Polio-Poliovirus,Poliovirus is a highly contagious virus that only affects humans, muscle aches, and abdominal pain are a few of the possible symptoms of polio.How do you diagnose polio?in order to diagnose polio, the doctor will ask the patient several questions and perform a physical exam. This article takes an in-depth look at the process of diagnosing polio.','Polio');


insert into vacc_info values('6 weeks','Hepatitis B Vaccine 2nd dose','Hepatitis B is a potentially deadly infection of the liver that kills about 500,000 to 700,000 people each year, mostly in developing countries. The virus is spread perinatally from an infected mother to her infant at birth, from child to child, through unsafe injections and transfusions, and through sexual contact. Currently, there is no effective treatment for the disease. Hepatitis B vaccines have been shown to be about 95 percent protective against the disease when used correctly. Hepatitis B resources on the Vaccine Resource Library were mainly gathered during PATH?s Children?s Vaccine Program, which conducted activities with hepatitis B vaccine.','cancer,jaundice (yellowing of the eyes and skin), dark urine, loss of appetite,AIDS-causing virus, HIV');


insert into vacc_info values('6 weeks','Pneumococcal 2nd dose','Pneumococcal disease,The pneumococcus bacterium (Streptococcus pneumoniae) is responsible for nearly one million deaths of children less than five years old each year. It can cause pneumonia, meningitis (inflammation of the covering of the brain), otitis media (inner ear infections), and bacteremia (blood stream infection). The bacteria normally are carried in the nose or upper throat and are spread through sneezing, coughing, or speaking closely with an infected person. Drugs such as penicillin are generally effective for treating pneumococcal disease, but antibiotic-resistant pneumococcus is becoming more common worldwide. This situation makes prevention of the disease, through widespread use of pneumococcal vaccines, even more important.Pneumococcal vaccines.','pneumococcal disease,pneumonia, meningitis (inflammation of the covering of the brain), otitis media (inner ear infections), and bacteremia (blood stream infection)');


insert into vacc_info values('10 weeks','DPT 2nd Dose:','DPT (also DTP and DTwP) refers to a class of combination vaccines against three infectious diseases in humans: diphtheria, pertussis (whooping cough) and tetanus. The vaccine components include diphtheria and tetanus toxoids, and killed whole cells of the organism that causes pertussis (wP). DTaP and Tdap refer to similar combination vaccines in which the pertussis component is acellular. The usual course of childhood immunization is five doses between 2 months and 15 years. For adults, separate combination vaccines are used that adjust the relative concentrations of their components.Tetanus (also called lockjaw) is a bacterial infection that causes severe and painful muscle spasms, seizures, and paralysis. Ten percent of reported cases end in death.','diphtheria, tetanus, and pertussis (whooping cough).');


insert into vacc_info values('10 weeks','Haemophilus Influenzae B Vaccine - 2nd Dose','Haemophilus influenzae type b (Hib) Hib mainly affects children under five years of age and is a significant cause of meningitis (inflammation of the covering of the brain) and bacterial pneumonia in children.Hib does not cause the ?flu?. Hib can leave children with permanent neurological disabilities, including brain damage, hearing loss, and mental retardation.Hib normally establishes itself in the nose or upper throat and is spread through sneezing, coughing, or speaking closely with an infected person. Children often carry Hib bacteria without showing any signs or symptoms(asymptomatic carriers), but they can still infect others.','Flu,HIV,brain damage,hearing loss,mentalretardation');


insert into vacc_info values('10 weeks','Oral Polio Vaccine - 3rd Dose','Oral polio vaccine (OPV) is a live-attenuated vaccine, produced by the passage of the virus through non-human cells at a sub-physiological temperature, which produces spontaneous mutations in the viral genome.Polio Disease are contagious illness that used to be very common in the United States. Causes of Polio-Poliovirus,Poliovirus is a highly contagious virus that only affects humans, muscle aches, and abdominal pain are a few of the possible symptoms of polio.How do you diagnose polio?in order to diagnose polio, the doctor will ask the patient several questions and perform a physical exam. This article takes an in-depth look at the process of diagnosing polio.','Polio');


insert into vacc_info values('14 weeks','DPT 3rd Dose:','DPT (also DTP and DTwP) refers to a class of combination vaccines against three infectious diseases in humans: diphtheria, pertussis (whooping cough) and tetanus. The vaccine components include diphtheria and tetanus toxoids, and killed whole cells of the organism that causes pertussis (wP). DTaP and Tdap refer to similar combination vaccines in which the pertussis component is acellular. The usual course of childhood immunization is five doses between 2 months and 15 years. For adults, separate combination vaccines are used that adjust the relative concentrations of their components.Tetanus (also called lockjaw) is a bacterial infection that causes severe and painful muscle spasms, seizures, and paralysis. Ten percent of reported cases end in death.','diphtheria, tetanus, and pertussis (whooping cough).');


insert into vacc_info values('14 weeks','Haemophilus Influenzae B Vaccine - 3rd Dose','Haemophilus influenzae type b (Hib) Hib mainly affects children under five years of age and is a significant cause of meningitis (inflammation of the covering of the brain) and bacterial pneumonia in children.Hib does not cause the ?flu?. Hib can leave children with permanent neurological disabilities, including brain damage, hearing loss, and mental retardation.Hib normally establishes itself in the nose or upper throat and is spread through sneezing, coughing, or speaking closely with an infected person. Children often carry Hib bacteria without showing any signs or symptoms(asymptomatic carriers), but they can still infect others.','Flu,HIV,brain damage,hearing loss,mentalretardation');


insert into vacc_info values('14 weeks','Oral Polio Vaccine - 4th Dose','Oral polio vaccine (OPV) is a live-attenuated vaccine, produced by the passage of the virus through non-human cells at a sub-physiological temperature, which produces spontaneous mutations in the viral genome.Polio Disease are contagious illness that used to be very common in the United States. Causes of Polio-Poliovirus,Poliovirus is a highly contagious virus that only affects humans, muscle aches, and abdominal pain are a few of the possible symptoms of polio.How do you diagnose polio?in order to diagnose polio, the doctor will ask the patient several questions and perform a physical exam. This article takes an in-depth look at the process of diagnosing polio.','Polio');


insert into vacc_info values('14 weeks','Hepatitis B Vaccine 3rd dose','Hepatitis B is a potentially deadly infection of the liver that kills about 500,000 to 700,000 people each year, mostly in developing countries. The virus is spread perinatally from an infected mother to her infant at birth, from child to child, through unsafe injections and transfusions, and through sexual contact. Currently, there is no effective treatment for the disease. Hepatitis B vaccines have been shown to be about 95 percent protective against the disease when used correctly. Hepatitis B resources on the Vaccine Resource Library were mainly gathered during PATH?s Children?s Vaccine Program, which conducted activities with hepatitis B vaccine.','cancer,jaundice (yellowing of the eyes and skin), dark urine, loss of appetite,AIDS-causing virus, HIV');


insert into vacc_info values('6 months','Influenza Vaccine','Vaccines against seasonal influenza are made yearly to defend against currently circulating strains; however, vaccines that can be produced quickly, affordably, and in mass quantity to respond to a potential influenza pandemic in real-time are not yet available.The most common method of influenza transmission is human-to-human, although animal-to-human transmission is possible. A person may infect others even though they seemingly have no influenza symptoms. Up to now, one of the deadliest influenza strains, avian influenza A (H5N1), is fortunately not easily spread from human-to-human; however, public health leaders are following the virus closely to see if it will evolve into a form that spreads efficiently from human to human. Influenza can be treated with antiviral drugs, which can lessen the severity of disease and are effective against influenza virus types A and B. Influenza vaccines.','Influenza disease,influenza A,influenza B, and influenza C,fever, headache, cough, tiredness, sore throat, runny or stuffy nose, body aches, and diarrhea or vomiting');


insert into vacc_info values('7 months','Influenza Vaccine','Vaccines against seasonal influenza are made yearly to defend against currently circulating strains; however, vaccines that can be produced quickly, affordably, and in mass quantity to respond to a potential influenza pandemic in real-time are not yet available.The most common method of influenza transmission is human-to-human, although animal-to-human transmission is possible. A person may infect others even though they seemingly have no influenza symptoms. Up to now, one of the deadliest influenza strains, avian influenza A (H5N1), is fortunately not easily spread from human-to-human; however, public health leaders are following the virus closely to see if it will evolve into a form that spreads efficiently from human to human. Influenza can be treated with antiviral drugs, which can lessen the severity of disease and are effective against influenza virus types A and B. Influenza vaccines','Influenza disease,influenza A,influenza B, and influenza C,fever, headache, cough, tiredness, sore throat, runny or stuffy nose, body aches, and diarrhea or vomiting')


